package-lock.json, package.json, src/App.js, src/components/Topbar.jsx, src/layout/MainLayout.jsx, src/styles/GlobalStyle.jsx
=> feat: 기초 구조 제작

src/App.js, src/pages/add-new-dancer/DancerRegistration.jsx
=> fix: 댄서 등록 페이지 Topbar 변경 사항 반영

.prettierrc, src/pages/registration/components/GenreSelector.jsx, src/pages/registration/components/ImagesUploader.jsx, src/pages/registration/newdancer/DancerForm.jsx, src/pages/registration/newdancer/DancerRegistration.jsx
=> feat: 댄서 등록 페이지 api 연결

src/pages/registration/components/GenreSelector.jsx, src/pages/registration/components/ImagesUploader.jsx, src/pages/registration/components/StarRating.jsx, src/pages/registration/components/TagSelector.jsx, src/pages/registration/components/VideoUploader.jsx, src/pages/registration/newclass/ClassForm.jsx, src/pages/registration/newclass/ClassRegistration.jsx, src/pages/registration/newdancer/DancerForm.jsx
close #78 
~~다른 필드는 경고 메시지 필요 없다네용 쩝스~~
- 사진 업로드 잘 되는 거 확인했습니다!
- 유튜브 URL이랑 파일 업로드 두 경우 모두 업로드 잘 되는 것도 확인했습니다!
- 수업 정보 잘 등록된 것까지 확인했습니다
요거 머지해도 댄스 수업 예약 탭에서 수업 잘 등록됐는지 확인하는 건
이 브랜치에서 작업한 게 아니라서 아직 안 보일 거예요
그치만 금방 pr 올릴 예정 (아마도)
가형언니 춤 추는 거 잘 봤슴다!!ㅎㅎ
=> feat: 댄스 수업 등록 페이지 api 연결

src/pages/mypage/components/myclass/MyLikeClass.jsx, src/pages/mypage/components/mydancer/MyLikeDancer.jsx
#89 
사진이 안나오는 이유는 .jpg로 지금 백엔드에 저장되어있어서 그런거 같아요! s3 버킷으로 이미지 등록하면 아마 나타날겁니당😎
진작 다 끝내긴 했었는데,, api 수정된다고 해서 기다렸습니당 할게,,, 더 많아졌네요 다시 으쌰으쌰 할게용
=> feat: 내가 찜한 수업 api 연결 

src/App.js, src/components/Alert.jsx, src/components/UserOverlay.jsx, src/pages/mypage/components/DancerPicture.jsx, src/pages/mypage/components/MypageGenre.jsx, src/pages/mypage/components/chatlist/MyChatList.jsx, src/pages/mypage/components/comment/CommentPost.jsx, src/pages/mypage/components/comment/CommentsReview.jsx, src/pages/mypage/components/comment/ReviewPage.jsx, src/pages/mypage/components/editprofile/ProfileDancer.jsx, src/pages/mypage/components/registerclass/MyRegisterClass.jsx, src/pages/mypage/components/registerclass/MyRegisterDetail.jsx, src/pages/mypage/components/review/MyReview.jsx, src/pages/mypage/components/review/ReviewDetail.jsx, src/pages/mypage/components/review/ReviewForm.jsx, src/pages/mypage/components/review/ReviewStar.jsx, src/pages/registration/newclass/ClassRegisterEdit.jsx
#97 
**많음 주의**
위에 사진 봐주세용 이 부분 근데 백엔드쪽이랑 뭔가 안맞아서 상의 후 수정 예정입니다~ 
잘 돌아가는거 확인했어용 추후에 사진 넣어놓던가 할게요!
---
대략적으로 큰 부분들만 사진에 넣어놨습니다! 이걸 하루만에 하려니까 진짜 살려주세요 나왔다....일단 api 연동은 다 해놔서 이제 자잘한 부분을 수정 할게요,,
이게 댄서 / 유저 입장 따로 구현하려니 머리가 터지고 터지고 터지네요 일단 대략적으로 해놓긴 했는데, 최종확인 후에 볼게용
대략 지금 생각나는거 적어놓을게욥
- 날짜 수정 
- 사진 s3에 넣는거 수정 
- 프로필 수정 유저 입장 
화이팅
=> feat: api 연결

netlify.toml
=> chore: 카카오 수정

src/api/formatDate.js, src/pages/reservation/ClassReservation.jsx, src/pages/reservation/ReviewDetailPage.jsx, src/pages/reservation/components/tabs/detail/DetailTab.jsx, src/pages/reservation/components/tabs/review/Review.jsx
=> chore: 수업 예약 페이지 디테일 수정

src/pages/mypage/components/chatlist/MyChatList.jsx, src/pages/mypage/components/myclass/MyLikeClass.jsx, src/pages/mypage/components/registerclass/MyRegisterClass.jsx, src/pages/mypage/components/registerclass/MyRegisterDetail.jsx, src/pages/mypage/components/review/MyReview.jsx, src/pages/mypage/components/review/PhotoUpload.jsx
#116 
- photo s3 upload 완료
- 사진들 안뜨는거 수정 완료
x
=> chore: 전체적인 수정

src/pages/KakaoRedirectHandler.jsx
=> feat: api 변경

src/pages/mypage/components/review/PhotoUpload.jsx, src/pages/mypage/components/review/ReviewDetail.jsx, src/pages/mypage/components/review/ReviewForm.jsx, src/pages/reservation/ReviewDetailPage.jsx
=> chore: 이미지 수정 

src/pages/mypage/components/review/ReviewForm.jsx
=> chore: 수업 후기 이미지 수정

src/api/schema.js
=> fix: 해시태그 스키마 오타 수정

src/pages/mypage/components/info/MyInfo.jsx, src/pages/profile/components/IntroduceTab.jsx, src/pages/profile/components/Profile.jsx
=> 댄서 프로필 상세 장보 조회 수정

src/pages/mypage/components/chatlist/MyChatList.jsx, src/pages/mypage/components/myclass/MyLikeClass.jsx, src/pages/mypage/components/mydancer/MyLikeDancer.jsx, src/pages/mypage/components/review/MyReview.jsx
=> feat: data가 없을때 text 출력

package-lock.json, package.json, src/pages/profile/DancerProfile.tsx, src/pages/profile/components/ClassTab.tsx, src/pages/profile/components/DancerBoard.tsx, src/pages/profile/components/IntroduceTab.tsx, src/pages/profile/components/Profile.tsx
#146 
일단 댄서 페이지 TS로 변환을 마쳤고 에러 뜨는 거도 없는 걸 확인했습니다
실제로 못 봐서 완벽하게 됐는지는 의문인데 뭐 일단은 에러 없으니 ㅎㅎ
=> refactor: 댄서 페이지 TS로 변환

src/api/api.ts, src/pages/KakaoRedirectHandler.tsx, src/pages/Signup/Signup1.tsx, src/pages/Signup/Signup2.tsx, src/pages/Signup/Signup3.tsx, src/pages/Signup/components/Overlay.tsx, src/pages/profile/components/DancerBoard.tsx
ts 변환
#155 
로그인, 회원가입 페이지, api 페이지  ts 변환 완료
=> refactor: 로그인, 회원가입 페이지 ts 변환

src/hooks/registration/useValidation.ts, src/pages/registration/_components/ImagesUploader.tsx, src/pages/registration/_components/Inputs.tsx, src/pages/registration/_components/RegisterComplete.tsx, src/pages/registration/_components/StarRating.tsx, src/pages/registration/_components/VideoUploader.tsx, src/pages/reservation/ClassList.tsx, src/pages/reservation/ClassReservation.tsx, src/pages/reservation/ReviewDetailPage.tsx, src/pages/reservation/_components/Level.tsx, src/pages/reservation/_components/tabs/detail/DetailTab.tsx, src/pages/reservation/_components/tabs/review/Review.tsx
#158 
-[x] @ 경로 삭제 → 상대 경로 수정
-[x] `ReactComponent` 사용하도록 svg 파일 import 방식 수정
X
=> fix: 등록, 예약 페이지 오류 수정

src/components/Comunity/CommunityList.tsx, src/layout/CommunityLayout.tsx, src/layout/SearchWrapper.tsx, src/pages/Community/CommunityPostPage.tsx
=> fix: 커뮤니티, 메인 페이지 버그 잡기

src/components/UserOverlay.tsx, src/pages/mypage/components/editprofile/ProfileDancer.tsx, src/pages/mypage/components/info/MyInfo.tsx, src/pages/mypage/components/registerclass/MyRegisterClass.tsx, src/pages/mypage/components/registerclass/MyRegisterDetail.tsx, src/pages/mypage/components/review/MyReview.tsx
close #165 
에러 없는데 확인했어용 모두들 고생많았다👍
=> fix: 마이페이지 버그 

src/components/Home/Carousel.tsx, src/components/Home/ForDancer.tsx, src/components/Home/PassiveCarousel.tsx, src/hooks/useGetClass.ts, src/hooks/useGetDancer.ts, src/pages/HomePage.tsx, src/types/MainInterface.ts
=> [Fix] Home 화면 고치기

package-lock.json, package.json
=> deploy: 재배포

src/common/Search/SearchBar.tsx, src/components/UserOverlay.tsx, src/hooks/useFetchList.ts, src/hooks/useGetDancer.ts, src/pages/Community/CommunityPostPage.tsx, src/pages/LoginPage.tsx, src/pages/Signup/Signup2.tsx
=> fix: 안쓰는 레거시 정리

src/pages/HomePage.tsx
=> deploy: 배포 중 수정

src/pages/mypage/components/editprofile/ProfileDancer.tsx
=> fix: 배포 에러 해결

src/assets/shape/focusdcirclemobile.svg, src/common/DancerProfile/ClassTab.tsx, src/common/DancerProfile/DancerBoard.tsx, src/common/DancerProfile/IntroduceTab.tsx, src/common/DancerProfile/Profile.tsx, src/common/DancerProfile/SidebarMobile.tsx, src/pages/DancerProfile/DancerProfile.tsx, src/pages/Signup/Signup2.tsx, src/pages/Signup/Signup4.tsx
#187 
댄서 프로필 반응형을 구현하였습니다.
채팅 버튼 미로그인 시에 안  뜨게 작업하였고 찜 상태도 반영될 수 있도록 변경하였습니다.
=> fix: 댄서 프로필 페이지 반응형 구현
